services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - DATABASE_URI=postgres://postgres:postgres@postgres/postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql
